"""Add country code to user

Revision ID: e1c6d68d2b25
Revises: 17d565195950
Create Date: 2026-01-01 21:44:00.600335

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1c6d68d2b25"
down_revision: Union[str, None] = "17d565195950"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "country_code", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "country_code")
    # ### end Alembic commands ###
